### ISSUE TITLE
Not working with TypeDoc 0.15.0

### ISSUE THREAD

**Issue by NoralK** [christopherthielen/typedoc-plugin-single-line-tags#377]
I am getting this error when I try using the plugin

```
C:\Temp\MV-1>typedoc --slt Static,Final
Error: The plugin C:\Temp\MV-1\node_modules\typedoc-plugin-single-line-tags could not be loaded.

TypeError: Class constructor ConverterComponent cannot be invoked without 'new'
    at new SingleLineTagsPlugin (C:\Temp\MV-1\node_modules\typedoc-plugin-single-line-tags\plugin.js:39:46)
    at Converter.addComponent (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\utils\component.js:123:19)
    at Converter.addComponent (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\converter\converter.js:25:33)
    at module.exports (C:\Temp\MV-1\node_modules\typedoc-plugin-single-line-tags\index.js:12:17)
    at PluginHost.load (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\utils\plugins.js:36:21)
    at CliApplication.bootstrap (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\application.js:42:22)
    at CliApplication.bootstrap (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\cli.js:24:30)
    at new Application (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\application.js:31:14)
    at new CliApplication (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\dist\lib\cli.js:22:1)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\bin\typedoc:4:1)

Using TypeScript 3.5.3 from C:\Users\User\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
Rendering [========================================] 100%
Error: Documentation could not be generated due to the errors above.
```

Any ideas?

**Comment by LydGol90** [comment]
Also seeing this issue @NoralK did you find a solution? I am on typedoc 0.16.10

**Comment by ScarletFlash** [comment]
Still relevant
